import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { readFile } from 'node:fs/promises';
const base = process.env.TEST_DATABASE_URL;
if (!base || !['127.0.0.1','localhost'].includes(new URL(base).hostname)) throw new Error('TEST_DATABASE_URL must name a disposable localhost database');
const schema = `card_review_${randomUUID().replaceAll('-','')}`;
const setup = new pg.Pool({connectionString:base});
await setup.query(`CREATE SCHEMA ${schema}`);
try {
 for (const table of ['users','cards','card_requests','card_actions','customer_subscriptions']) await setup.query(`CREATE TABLE ${schema}.${table} (LIKE public.${table} INCLUDING ALL)`);
 const url = new URL(base); url.searchParams.set('options',`-c search_path=${schema},public`);
 process.env.DATABASE_URL=url.toString();process.env.NODE_ENV='test';
 const {getPool,q,one} = await import('../src/db.js');
 const migration=await readFile(new URL('../src/migrations/021_card_approval.sql',import.meta.url),'utf8');await q(migration);
 process.env.CARD_IDENTITY_KEY="12".repeat(32);
 const {approveCardRequest,finishReplacement,encryptIdentity}=await import('../src/lib/card-approval.js');
 const admin=await one("INSERT INTO users(email,password_hash,role) VALUES('admin@test.invalid','unused','admin') RETURNING id");
 const fixture=async name=>{const user=await one("INSERT INTO users(email,password_hash,role,full_name) VALUES($1,'unused','customer','Test Customer') RETURNING id",[`${name}@test.invalid`]);return one("INSERT INTO card_requests(user_id,label,full_name,plan_code,payment_reference,payment_status,verification_status,status,fee_kobo,charged_kobo) VALUES($1,'Fuel Card','Test Customer','gold',$2,'paid','pending','pending_verification',0,350000) RETURNING *",[user.id,randomUUID()]);};
 let calls=0;
 const issuer={enabled:()=>true,createCustomer:async()=>({id:'customer'}),issueCard:async()=>{calls++;await new Promise(r=>setTimeout(r,25));return {id:`card-${calls}`,maskedPan:'****1234',expiryMonth:9,expiryYear:2030};}};
 const first=await fixture('concurrent');await q('UPDATE card_requests SET bvn_encrypted=$2 WHERE id=$1',[first.id,encryptIdentity('21234567890')]);
 const results=await Promise.allSettled([approveCardRequest(first.id,admin.id,null,issuer),approveCardRequest(first.id,admin.id,null,issuer)]);
 assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(calls,1);
 const replay=await approveCardRequest(first.id,admin.id,null,issuer);assert.equal(replay.alreadyApproved,true);assert.equal(calls,1);
 assert.equal(Number((await one('SELECT count(*) FROM cards WHERE owner_user_id=$1',[first.user_id])).count),1);
 assert.equal((await one('SELECT status FROM customer_subscriptions WHERE user_id=$1',[first.user_id])).status,'active');
 const uncertain=await fixture('uncertain');await q('UPDATE card_requests SET bvn_encrypted=$2 WHERE id=$1',[uncertain.id,encryptIdentity('21234567890')]);let uncertainCalls=0;
 const failing={...issuer,issueCard:async()=>{uncertainCalls++;throw new Error('Provider timeout after submission');}};
 await assert.rejects(()=>approveCardRequest(uncertain.id,admin.id,null,failing),/timeout/);
 await assert.rejects(()=>approveCardRequest(uncertain.id,admin.id,null,failing),/reconciliation/);assert.equal(uncertainCalls,1);
 assert.equal((await one('SELECT issuance_state FROM card_requests WHERE id=$1',[uncertain.id])).issuance_state,'review_required');
 await approveCardRequest(uncertain.id,admin.id,{providerId:'reconciled-card',maskedPan:'•••• •••• •••• 5678',expiry:'09/30',customerId:'customer'},issuer);
 assert.equal((await one('SELECT status FROM card_requests WHERE id=$1',[uncertain.id])).status,'approved');assert.equal(calls,1);
 const abandoned=await fixture('abandoned');await q("UPDATE card_requests SET issuance_state='creating',updated_at=now()-interval '3 minutes' WHERE id=$1",[abandoned.id]);
 await approveCardRequest(abandoned.id,admin.id,{providerId:'abandoned-card',maskedPan:'•••• •••• •••• 1111',expiry:'09/30',customerId:'customer'},issuer);
 assert.equal((await one('SELECT status FROM card_requests WHERE id=$1',[abandoned.id])).status,'approved');
 const old = await one("INSERT INTO cards(owner_user_id,label,status,sudo_card_id,sudo_customer_id,balance_kobo) VALUES($1,'Old card','terminated','old-card','customer',0) RETURNING id",[first.user_id]);
 const replacementDetails={providerId:'replacement-card',maskedPan:'•••• •••• •••• 9012',expiry:'12/30'};
 const replaced=await finishReplacement(old.id,replacementDetails,admin.id);
 const repeated=await finishReplacement(old.id,replacementDetails,admin.id);
 assert.equal(replaced.id,repeated.id);
 assert.equal(Number((await one('SELECT balance_kobo FROM cards WHERE id=$1',[replaced.id])).balance_kobo),0);
 assert.equal((await one('SELECT status FROM cards WHERE id=$1',[old.id])).status,'replaced');
 const funded = await one("INSERT INTO cards(owner_user_id,status,balance_kobo) VALUES($1,'terminated',1000) RETURNING id",[first.user_id]);
 await assert.rejects(()=>finishReplacement(funded.id,{...replacementDetails,providerId:'must-not-exist'},admin.id),/withdraw/);
 assert.equal((await one("SELECT count(*) FROM cards WHERE sudo_card_id='must-not-exist'")).count,'0');
 await getPool().end();
 console.log('Card approval integration passed: concurrent claims, replay, subscription activation, ambiguous failure, reconciliation, idempotent replacement and no balance duplication.');
} finally {await setup.query(`DROP SCHEMA ${schema} CASCADE`);await setup.end();}
