"use client";
import { useCallback, useEffect, useState } from "react";
import { api } from "@/lib/services/client";
type Application = { id:string; full_name:string;email:string;bvn_last_four:string;date_of_birth:string;postal_code:string;identity_phone:string;address:string;city:string;state:string;plan_code:string;status:string;verification_status:string;issuance_state:string;rejection_reason:string };
export function CardApprovalQueue() {
 const [rows,setRows]=useState<Application[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [reason,setReason]=useState<Record<string,string>>({});const [identities,setIdentities]=useState<Record<string,string>>({});const [providerIds,setProviderIds]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{const r=await api.request<{requests:Application[]}>("/api/admin/card-requests");setRows(r.requests);setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to load card applications");}},[]);
 useEffect(()=>{void load();},[load]);
 async function decide(row:Application,action:"approve"|"reject"|"reconcile") {setBusy(row.id);setError("");try{await api.request(`/api/admin/card-requests/${row.id}/${action}`,{method:"POST",body:JSON.stringify(action==="reject"?{reason:reason[row.id]}:action==="reconcile"?{providerCardId:providerIds[row.id]}:{})});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to review application");}finally{setBusy("");}}
 return <section className="mx-5 mb-8 rounded-xl border border-obligon-border bg-white p-6 sm:mx-8" aria-label="Customer card approvals"><div className="flex justify-between"><h2 className="text-xl font-bold">Customer card approval requests</h2><button type="button" onClick={()=>void load()}>Refresh</button></div><p className="mt-2 text-sm">Review paid identity applications before issuing virtual cards. Physical delivery is coming soon.</p>{error?<p role="alert" className="mt-3 text-red-700">{error}</p>:null}{rows.length===0?<p className="mt-4">No pending applications.</p>:rows.map(row=><article key={row.id} className="mt-4 border-t py-4"><h3 className="font-bold">{row.full_name} · {row.plan_code}</h3><p>{row.email} · BVN {identities[row.id] ?? `ending ${row.bvn_last_four}`}</p><button type="button" className="text-sm underline" onClick={async()=>{try{if(identities[row.id]){setIdentities({...identities,[row.id]:""});return;}const data=await api.request<{bvn:string}>(`/api/admin/card-requests/${row.id}/identity`);setIdentities({...identities,[row.id]:data.bvn});}catch(e){setError(e instanceof Error?e.message:"Unable to view identity");}}}>{identities[row.id]?"Hide identity":"Review full identity (audited)"}</button><p>{row.address}, {row.city}, {row.state}, {row.postal_code}</p><p>Date of birth: {row.date_of_birth} · Phone: {row.identity_phone}</p><p className="text-sm">{row.verification_status} · Issuance: {row.issuance_state}</p>{row.rejection_reason?<p>Rejected: {row.rejection_reason}</p>:["review_required","creating"].includes(row.issuance_state)?<div><label className="block">Verified issuer card ID<input className="ml-2 rounded border p-2" value={providerIds[row.id]??""} onChange={e=>setProviderIds({...providerIds,[row.id]:e.target.value})}/></label><button type="button" disabled={busy===row.id||!providerIds[row.id]} onClick={()=>void decide(row,"reconcile")} className="mt-2 rounded bg-obligon-green px-4 py-2 text-white">Reconcile existing issued card</button></div>:<div className="mt-3 flex flex-wrap gap-3"><button type="button" disabled={busy===row.id} onClick={()=>void decide(row,"approve")} className="rounded bg-obligon-green px-4 py-2 text-white">{busy===row.id?"Processing…":"Approve & issue"}</button><label>Rejection reason<input aria-label={`Rejection reason for ${row.full_name}`} className="ml-2 rounded border p-2" maxLength={500} value={reason[row.id]??""} onChange={e=>setReason({...reason,[row.id]:e.target.value})}/></label><button type="button" disabled={busy===row.id||(reason[row.id]??"").trim().length<5} onClick={()=>void decide(row,"reject")} className="rounded border px-4 py-2">Reject</button></div>}</article>)}<ReplacementReconciliation /></section>;
}

type Replacement = { id:string;holder_name:string;email:string;sudo_card_id:string };
function ReplacementReconciliation() {
 const [rows,setRows]=useState<Replacement[]>([]);const [ids,setIds]=useState<Record<string,string>>({});const [error,setError]=useState("");const [busy,setBusy]=useState("");
 const load=useCallback(async()=>{try{const response=await api.request<{requests:Replacement[]}>("/api/admin/card-replacements");setRows(response.requests);}catch(e){setError(e instanceof Error?e.message:"Unable to load replacements");}},[]);
 useEffect(()=>{void load();},[load]);
 return <div className="mt-8 border-t pt-4"><h3 className="font-bold">Issuer replacement reconciliation</h3>{error?<p role="alert">{error}</p>:null}{rows.length===0?<p className="mt-2 text-sm">No uncertain card replacements.</p>:rows.map(row=><div key={row.id} className="mt-4"><p>{row.holder_name} · {row.email}</p><p className="text-xs">Old issuer card: {row.sudo_card_id}. Confirm termination and locate the replacement in the issuer dashboard first.</p><label>Replacement issuer card ID<input className="ml-2 rounded border p-2" value={ids[row.id]??""} onChange={e=>setIds({...ids,[row.id]:e.target.value})}/></label><button type="button" className="ml-2 rounded border p-2" disabled={busy===row.id||!ids[row.id]} onClick={async()=>{setBusy(row.id);try{await api.request(`/api/admin/card-replacements/${row.id}/reconcile`,{method:"POST",body:JSON.stringify({providerCardId:ids[row.id]})});await load();}catch(e){setError(e instanceof Error?e.message:"Reconciliation failed");}finally{setBusy("");}}}>Verify & complete</button></div>)}</div>;
}
