import PDFDocument from "pdfkit";

function header(doc, title, subtitle) {
  doc.fontSize(22).fillColor("#0f172a").text("OBLIGON LTD", { continued: false });
  doc.moveDown(0.2).fontSize(11).fillColor("#64748b").text("Fleet fuel management • Lagos, Nigeria");
  doc.moveDown(1).fontSize(18).fillColor("#0f172a").text(title);
  if (subtitle) doc.fontSize(10).fillColor("#64748b").text(subtitle);
  doc.moveDown(1);
}

function table(doc, columns, rows) {
  const tableTop = doc.y + 10;
  const rowHeight = 24;
  let x = doc.page.margins.left;
  doc.rect(doc.page.margins.left, tableTop, doc.page.width - doc.page.margins.left * 2, rowHeight).fill("#f1f5f9");
  doc.fillColor("#0f172a").fontSize(9);
  columns.forEach((c) => {
    doc.text(c.label, x + 6, tableTop + 8, { width: c.width - 10 });
    x += c.width;
  });
  let y = tableTop + rowHeight;
  doc.fontSize(9).fillColor("#334155");
  rows.forEach((row, ri) => {
    if (y + rowHeight > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      y = doc.page.margins.top;
    }
    if (ri % 2 === 1) {
      doc.rect(doc.page.margins.left, y, doc.page.width - doc.page.margins.left * 2, rowHeight).fill("#f8fafc");
      doc.fillColor("#334155");
    }
    x = doc.page.margins.left;
    columns.forEach((c) => {
      doc.text(String(row[c.key] ?? ""), x + 6, y + 8, { width: c.width - 10 });
      x += c.width;
    });
    y += rowHeight;
  });
  doc.y = y + 10;
}

function streamBuffer(doc) {
  return new Promise((resolve) => {
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.end();
  });
}

export async function receiptPdf({ reference, createdAt, station, fuelType, litres, amountLabel, status, vehicle, holder }) {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  header(doc, "Fuel Purchase Receipt", `Reference ${reference}`);
  doc.fontSize(10).fillColor("#334155");
  doc.text(`Date: ${new Date(createdAt).toLocaleString("en-NG")}`);
  doc.text(`Station: ${station}`);
  doc.text(`Card holder: ${holder ?? "—"}`);
  if (vehicle) doc.text(`Vehicle: ${vehicle}`);
  doc.moveDown(1);
  table(
    doc,
    [
      { key: "item", label: "Item", width: 200 },
      { key: "qty", label: "Quantity", width: 120 },
      { key: "amount", label: "Amount", width: 180 }
    ],
    [{ item: fuelType, qty: `${litres} L`, amount: amountLabel }]
  );
  doc.fontSize(12).fillColor("#0f172a").text(`Total: ${amountLabel}`, { align: "right" });
  doc.moveDown(2).fontSize(9).fillColor("#64748b").text(`Status: ${status} • Generated by Obligon LTD`, { align: "center" });
  return streamBuffer(doc);
}

export async function invoicePdf({ number, createdAt, orgName, planName, amountLabel, status, periodLabel }) {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  header(doc, `Invoice ${number}`, `Billed to ${orgName}`);
  doc.fontSize(10).fillColor("#334155");
  doc.text(`Issued: ${new Date(createdAt).toLocaleDateString("en-NG")}`);
  doc.text(`Plan: ${planName}`);
  doc.text(`Period: ${periodLabel}`);
  doc.moveDown(1);
  table(
    doc,
    [
      { key: "desc", label: "Description", width: 300 },
      { key: "amount", label: "Amount", width: 200 }
    ],
    [{ desc: `${planName} subscription — ${periodLabel}`, amount: amountLabel }]
  );
  doc.fontSize(12).fillColor("#0f172a").text(`Total: ${amountLabel}`, { align: "right" });
  doc.moveDown(1).fontSize(11).fillColor("#059669").text(`Status: ${status.toUpperCase()}`, { align: "right" });
  doc.moveDown(2).fontSize(9).fillColor("#64748b").text("Payable via your billing dashboard. Generated by Obligon LTD.", { align: "center" });
  return streamBuffer(doc);
}

export async function reportPdf({ title, subtitle, columns, rows }) {
  const doc = new PDFDocument({ size: "A4", margin: 50, layout: columns.length > 4 ? "landscape" : "portrait" });
  header(doc, title, subtitle);
  table(doc, columns, rows);
  doc.moveDown(1).fontSize(9).fillColor("#64748b").text(`Generated ${new Date().toLocaleString("en-NG")} • Obligon LTD`, { align: "center" });
  return streamBuffer(doc);
}
