"use client";
import * as React from 'react';
import { authenticatedRequest } from '@/lib/services';
interface Pricing {stations:Array<{id:string;name:string}>;prices:Array<{stationId:string;fuelType:string;price:number}>;discounts:Array<{id:string;station_id:string;fuel_type:string;rate_bp:number;starts_at:string;ends_at:string;status:string;review_reason:string|null}>}
export function StationDiscounts(){
 const [data,setData]=React.useState<Pricing|null>(null),[station,setStation]=React.useState(''),[fuel,setFuel]=React.useState(''),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
 const load=React.useCallback(async()=>{try{const d=await authenticatedRequest<Pricing>('/api/partner/pricing');setData(d);setStation(s=>s||d.stations[0]?.id||'');}catch(e){setError((e as Error).message);}},[]);
 React.useEffect(()=>{void load();},[load]);
 const prices=data?.prices.filter(p=>p.stationId===station)??[];
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');try{await authenticatedRequest('/api/partner/discounts',{method:'POST',body:JSON.stringify({stationId:station,fuelType:fuel||prices[0]?.fuelType,discountPercent:Number(form.get('rate')),startsAt:new Date(String(form.get('starts'))).toISOString(),endsAt:new Date(String(form.get('ends'))).toISOString()})});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="mt-8 rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Scheduled station discounts</h2><p className="mt-2 text-sm">Admin approval is required before a discount applies. Adjust or extend a discount by submitting a new date range. Customers receive a price reduction; the same discount amount is paid to Obligon from your revenue.</p>{error&&<p role="alert" className="my-3 text-red-700">{error}</p>}<form onSubmit={submit} className="mt-4 grid gap-4 sm:grid-cols-2"><label>Station<select className="block w-full rounded border p-2" value={station} onChange={e=>{setStation(e.target.value);setFuel('');}} required>{data?.stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Fuel<select className="block w-full rounded border p-2" value={fuel||prices[0]?.fuelType||''} onChange={e=>setFuel(e.target.value)} required>{prices.map(p=><option key={p.fuelType}>{p.fuelType}</option>)}</select></label><label>Discount (%)<input className="block w-full rounded border p-2" name="rate" type="number" min="0.01" max="49.99" step="0.01" required/></label><label>Starts (local time)<input className="block w-full rounded border p-2" name="starts" type="datetime-local" required/></label><label>Ends (local time)<input className="block w-full rounded border p-2" name="ends" type="datetime-local" required/></label><button className="self-end rounded bg-obligon-green p-3 text-white disabled:opacity-50" disabled={busy||!prices.length}>Request admin approval</button></form><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Station / fuel</th><th>Discount</th><th>Date range</th><th>Review</th></tr></thead><tbody>{data?.discounts.map(d=><tr key={d.id} className="border-t"><td className="p-2">{data.stations.find(s=>s.id===d.station_id)?.name} / {d.fuel_type}</td><td>{d.rate_bp/100}%</td><td>{new Date(d.starts_at).toLocaleString()} – {new Date(d.ends_at).toLocaleString()}</td><td>{d.status}{d.review_reason&&<p>{d.review_reason}</p>}</td></tr>)}</tbody></table></div></section>;
}
